image: docker:dind

stages:
- patch
- build
- test
- deploy_pypi
- deploy_pages

before_script:
- dockerd &
- sleep 5
- docker info
- apk update
- apk upgrade
- apk add make git python3 python3-dev build-base libffi libffi-dev
- apk-install curl ca-certificates bash openssl-dev readline-dev bzip2-dev sqlite-dev ncurses-dev linux-headers
- curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer -o /pyenv-installer && \
  touch /root/.bashrc && \
  /bin/ln -s /root/.bashrc /root/.bash_profile && \
  /bin/bash /pyenv-installer && \
  rm /pyenv-installer && \
  echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile && \
  echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile && \
  echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
- pyenv install 2.7
- pyenv install 3.3
- pyenv install 3.4
- pyenv install 3.5
- pyenv install 3.6

patch:
  stage: patch
  script:
  - python3 patch_swagger.py
  - python3 -m ensurepip
  - pip3 install prance
  - prance validate swagger.json
  artifacts:
    paths:
    - swagger.json

build:
  stage: build
  image: docker:latest
  services:
  - docker:dind
  script:
  - |
    docker run --rm --user `id -u`:`id -g` -v ${PWD}:/local openapitools/openapi-generator-cli:v3.2.2 \
    generate -i /local/swagger.json \
    --git-user-id rienafairefr \
    --git-repo-id pyrebrickable \
    -g python -o /local/api -DprojectName=pyrebrickable_api -DpackageName=rebrickable_api \
    -DpackageVersion="$(VERSION)" -DappDescription="This is rebrickable_api, an autogenerated package to access www.rebrickable.com"\
    -DappName="pyrebrickable-api" -DinfoEmail="rienafairefr@gmail.com"
  - make build_docs
  dependencies:
  - patch
  artifacts:
    paths:
    - api/
    - docs/

test:
  stage: test
  script:
  - pip3 install -r dev-requirements.txt
  - tox
  dependencies:
  - build

deploy_pypi:
  stage: deploy_pypi
  script: VERSION=$CI_COMMIT_TAG make deploy_pypi
  only:
  - master
  - tags

deploy_pages:
  stage: deploy_pages
  script:
  - make build_docs
  artifacts:
    paths:
    - docs
  only:
  - master
  - tags
