image: docker:latest

services:
- name: docker:dind
  command: ["--experimental"]

stages:
- build
- test
- deploy_pypi
- deploy_pages

job_build:
  stage: build
  script:
  - apk update && apk add make
  - make generate_api

job_test:
  stage: test
  script:
  - pip install -r dev-requirements.txt
  - make validate_spec
  - tox

job_deploy_pypi:
  stage: deploy_pypi
  script: VERSION=$CI_COMMIT_TAG make deploy_pypi
  only:
  - master
  - tags

pages:
  stage: deploy_pages
  script:
  - make build_docs
  artifacts:
    paths:
    - docs
  only:
  - master
  - tags
