image: docker:dind

stages:
- build
- test
- deploy_pypi
- deploy_pages

before_script:
- dockerd &
- sleep 5
- docker info
- apk update
- apk upgrade
- apk add python3 build-base
- apk update && apk add make


buildd:
  stage: build
  script:
  - make generate_api
  artifacts:
    paths:
    - api/

test:
  stage: test
  script:
  - pip3 install -r dev-requirements.txt
  - make validate_spec
  - tox
  dependencies:
  - build

deploy_pypi:
  stage: deploy_pypi
  script: VERSION=$CI_COMMIT_TAG make deploy_pypi
  only:
  - master
  - tags

deploy_pages:
  stage: deploy_pages
  script:
  - make build_docs
  artifacts:
    paths:
    - docs
  only:
  - master
  - tags
